-- MySQL Script generated by MySQL Workbench
-- Sat Jul 17 15:37:13 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema prestamos_db
-- -----------------------------------------------------
-- base de datos para prestamos

-- -----------------------------------------------------
-- Schema prestamos_db
--
-- base de datos para prestamos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `prestamos_db` DEFAULT CHARACTER SET utf8 ;
USE `prestamos_db` ;

-- -----------------------------------------------------
-- Table `prestamos_db`.`Customer_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prestamos_db`.`Customer_type` (
  `idCustomerType` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCustomerType`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prestamos_db`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prestamos_db`.`Customer` (
  `idCustomer` INT NOT NULL AUTO_INCREMENT,
  `customer_type` INT NOT NULL DEFAULT 1,
  `numIdent` VARCHAR(20) NOT NULL,
  `custName` VARCHAR(45) NOT NULL,
  `custLastName` VARCHAR(45) NOT NULL,
  `cellPhone` VARCHAR(20) NULL,
  `phone` VARCHAR(45) NULL,
  `phoneTwo` VARCHAR(45) NULL,
  `address` VARCHAR(100) NULL,
  `email` VARCHAR(100) NULL,
  `registerDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `registerBy` INT NULL,
  `active` VARCHAR(1) NOT NULL DEFAULT 'Y',
  PRIMARY KEY (`idCustomer`),
  INDEX `fk_Customer_Customer1_idx` (`registerBy` ASC),
  INDEX `fk_Customer_Customer_type1_idx` (`customer_type` ASC),
  CONSTRAINT `fk_Customer_Customer1`
    FOREIGN KEY (`registerBy`)
    REFERENCES `prestamos_db`.`Customer` (`idCustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Customer_Customer_type1`
    FOREIGN KEY (`customer_type`)
    REFERENCES `prestamos_db`.`Customer_type` (`idCustomerType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Información de los clientes';


-- -----------------------------------------------------
-- Table `prestamos_db`.`Loan_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prestamos_db`.`Loan_type` (
  `idLoanType` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idLoanType`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prestamos_db`.`Loan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prestamos_db`.`Loan` (
  `idLoan` INT NOT NULL AUTO_INCREMENT,
  `custId` INT NOT NULL,
  `valueIni` DECIMAL(15,2) NOT NULL,
  `valueNow` DECIMAL(15,2) NOT NULL,
  `payUntil` DATETIME NOT NULL,
  `idLoanType` INT NOT NULL,
  `prePayment` VARCHAR(1) NOT NULL DEFAULT 'Y',
  `date` DATETIME NOT NULL,
  `percentage` DECIMAL(5,2) NOT NULL,
  PRIMARY KEY (`idLoan`),
  INDEX `fk_Prestamo_Usuario_idx` (`custId` ASC),
  INDEX `fk_Loan_LoanType1_idx` (`idLoanType` ASC),
  CONSTRAINT `fk_Prestamo_Usuario`
    FOREIGN KEY (`custId`)
    REFERENCES `prestamos_db`.`Customer` (`idCustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Loan_LoanType1`
    FOREIGN KEY (`idLoanType`)
    REFERENCES `prestamos_db`.`Loan_type` (`idLoanType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Administra información de los prestamos a clientes';


-- -----------------------------------------------------
-- Table `prestamos_db`.`Payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prestamos_db`.`Payment` (
  `idPayment` INT NOT NULL AUTO_INCREMENT,
  `value` DECIMAL(15,2) NOT NULL,
  `date` DATETIME NOT NULL,
  `loanId` INT NOT NULL,
  `concept` VARCHAR(100) NOT NULL,
  `isPayToCapital` VARCHAR(1) NOT NULL,
  `lastDebt` DECIMAL(15,2) NOT NULL,
  `currentDebt` DECIMAL(15,2) NOT NULL,
  PRIMARY KEY (`idPayment`),
  INDEX `fk_Payment_Loan1_idx` (`loanId` ASC),
  CONSTRAINT `fk_Payment_Loan1`
    FOREIGN KEY (`loanId`)
    REFERENCES `prestamos_db`.`Loan` (`idLoan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prestamos_db`.`Parameters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prestamos_db`.`Parameters` (
  `idParameters` INT NOT NULL,
  `Description` VARCHAR(100) NOT NULL,
  `Value` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idParameters`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prestamos_db`.`Mortage_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prestamos_db`.`Mortage_data` (
  `idMortage_data` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(45) NULL,
  `mortage_number` VARCHAR(45) NOT NULL,
  `notary` VARCHAR(45) NULL,
  `mortage_type` VARCHAR(45) NULL,
  `comments` VARCHAR(300) NULL,
  `Loan_idLoan` INT NOT NULL,
  PRIMARY KEY (`idMortage_data`),
  INDEX `fk_Mortage_data_Loan1_idx` (`Loan_idLoan` ASC),
  UNIQUE INDEX `Loan_idLoan_UNIQUE` (`Loan_idLoan` ASC),
  CONSTRAINT `fk_Mortage_data_Loan1`
    FOREIGN KEY (`Loan_idLoan`)
    REFERENCES `prestamos_db`.`Loan` (`idLoan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
